[project]
name = "agent-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kohaku4869" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
agent-service = "agent_service:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"
